require('plugins/treesitter')
require('plugins/galaxyline')
require('plugins/lspconfig')
require('plugins/compe')
require('plugins/saga')
require('plugins/kind')

require('lsp/config')
require('lsp/efm')
require('lsp/tsserver')
require('lsp/graphql')
require('lsp/html')
require('lsp/css')
